### ISSUE TITLE
Try to answer some questions on the comments

### ISSUE THREAD

**Issue by ejgallego** [tomtomjhj/coq-lsp.nvim#1]
Hi @tomtomjhj , I'm Emilio, coq-lsp dev, thanks a lot for this!

Would you mind if I add a link from coq-lsp page to this project?

I took the liberty to answer a couple of comments you got on the code:

- `TODO: async vs. sync? When do we want to send this request?`
  Indeed, vscode client sends it on cursor movement _by default_ but note it is configurable. Yes, essentially this request is async, as it can take a while to compute, for example you can jump to a part of a file that needs to be checked, coq-lsp will then trigger checking as to answer the goal.
- `How to handle multiple in-flight requests?` As of now coq-lsp will just serve them sequentially, or even cancel them if an ulterior edit made the request stale. I want to keep the possiblity in the server of having several info requests concurrently, so I'd suggest that you just send a `$/cancelRequest` notification when a new in-flight request arrives.
- `How does the user know that the currently shown goal is the goal at the cursor?` here we follow what lean does and put the position / file information at the top of the goal buffer
- `Show spinner?` yes, that's a good idea, you can write something like "waiting for goals info at file:pos`
- `coq-lsp sometimes DOSes client. Crashes vscode and breaks nvim rpc stuff` , could you provide some more details on this, open an issue upstream? We will release 0.1.5 soon tho that includes some fixes.

**Comment by tomtomjhj** [comment]
Hi Emilio, thanks a lot for taking time to answer the questions!

> Would you mind if I add a link from coq-lsp page to this project?

Sounds good.

> Indeed, vscode client sends it on cursor movement by default but note it is configurable.
> [...]
> I'd suggest that you just send a `$/cancelRequest` notification when a new in-flight request arrives.

Thanks for suggestion. I'll implement this when I get some free time.

> could you provide some more details on this, open an issue upstream?

Unfortunately, I don't have reliable reproducer and debug log. All I remember is that vscode crashed with SIGILL, and nvim raised various errors related to its RPC implementation at which point nvim was hogging several gigabytes of memory. I'll file an upstream issue when I get a reproducer or debug log.

**Comment by tomtomjhj** [comment]
> I'd suggest that you just send a `$/cancelRequest` notification when a new in-flight request arrives.
> [...]
> here we follow what lean does and put the position / file information at the top of the goal buffer

I have implemented this. Closing.
