### ISSUE TITLE
What version of coq-lsp does this plugin support?

### ISSUE THREAD

**Issue by DieracDelta** [tomtomjhj/coq-lsp.nvim#4]
When I run this on HEAD of coq-lsp (ac2154bd0eb8668b62aacf5bdbea38540ade526f), I get a "document not ready" error. 

Things I've done:
- pull in HEAD of coq-lsp-nvim
- pull in HEAD of coqtail

set:
```vimscript
    let g:loaded_coqtail = 1
    let g:coqtail#supported = 0
```
Then call:
```lua
    require'coq-lsp'.setup{
      lsp = {
        cmd = { "path/to/coq/binary" } -- this must be overridden for me since I'm on nix and directly sticking this in from my flake
      }
    }
```

Happy to provide a minimal reproducible example if helpful! I'm hoping this is an easy fix.

**Comment by tomtomjhj** [comment]
I use coq-lsp 0.1.7, coq 8.17.1, nvim HEAD (0.9.1 works too). 

Please check if you can reproduce with 0.1.7

**Comment by DieracDelta** [comment]
Thanks for the reply! I am using coq-lsp 0.1.7, coq 8.18.0 compiled with OCaml 4.14.1. I'm not able to reproduce with vscode. That is, the lsp works as expected in vscode.

**Comment by DieracDelta** [comment]
Nevermind. It was an error in my lualine config that was causing this. I've since removed it and this plugin is working. Thanks for the responses!
