### ISSUE TITLE
Upstream the lspconfig configuration

### ISSUE THREAD

**Issue by Julian** [tomtomjhj/coq-lsp.nvim#5]
Hi there!

Would you happen to like to upstream the `nvim-lspconfig` that's here? I was just looking to send lspconfig a PR adding it for `coq-lsp` but then found this plugin. If you'd like to I'll wait for your PR, otherwise let me know and I can do so.

(Looking forward to trying out your plugin in general as well!)

**Comment by tomtomjhj** [comment]
Hi, I just made PR at lspconfig https://github.com/neovim/nvim-lspconfig/pull/2850. Thanks for reminder.
