### ISSUE TITLE
Is there a way to display messages, not just goals

### ISSUE THREAD

**Issue by dylech30th** [tomtomjhj/coq-lsp.nvim#6]
I just tried to use nvim to write coq instead of the CoqIDE, I love this plugin's interactivity as the cursor moves, but there is only a goal window, and no messages were shown, I'm wondering is there a way to see messages too?

**Comment by tomtomjhj** [comment]
Hi, please take a look at https://github.com/tomtomjhj/vscoq.nvim. It's similar to this plugin, but for vscoqtop. It also supports queries such as Search. Unfortunately, I don't have enough time to work on both plugins.

**Comment by tomtomjhj** [comment]
now the info panel shows the messages too: 268c5d52bd307d06775846994f3582f517f4ba0e

it's quite primitive at this point, but when I have time I'll explore better ways to display them (e.g., folding or command to show it)
